services:
  db:
    image: postgres:13.13
    ports:
     - 5432:5432
    environment:
      POSTGRES_PASSWORD: gamesapi
      POSTGRES_USER: gamesapi
      POSTGRES_DB: gamesapi
  web:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - 8000:8000
    environment:
      DB_DATABASE: gamesapi
      DB_USERNAME: gamesapi
      DB_PASSWORD: gamesapi
      DB_HOST: db

networks:
  web_net:
    driver: bridge
