apiVersion: apps/v1
kind: Deployment
metadata: 
  name: db
spec:
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: postgres:13.1
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: gamesapi
            - name: POSTGRES_USER
              value: gamesapi
            - name: POSTGRES_DB
              value: gamesapi
---
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  selector:
    app: db
  ports:
    - port: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubenews
spec:
  replicas: 10
  selector:
    matchLabels:
      app: kubenews
  template:
    metadata:
      labels:
        app: kubenews
    spec:
      containers:
      - name: kubenews
        image: nayannanara/games_api:v2
        ports:
        - containerPort: 8080
        env:
        - name: DB_DATABASE
          value: gamesapi
        - name: DB_PASSWORD
          value: gamesapi
        - name: DB_USERNAME
          value: gamesapi
        - name: DB_HOST
          value: db
---
apiVersion: v1
kind: Service
metadata:
  name: kubenews
spec:
  selector:
    app: kubenews
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer
