apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
spec:
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: postgres:13.1
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: gamesapi
            - name: POSTGRES_USER
              value: gamesapi
            - name: POSTGRES_DB
              value: gamesapi

---
apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  selector:
    app: db
  ports:
    - port: 5432

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 10
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: nayannanara/games_api:latest
          ports:
            - containerPort: 8000
          env:
            - name: DB_DATABASE
              value: gamesapi
            - name: DB_PASSWORD
              value: gamesapi
            - name: DB_USERNAME
              value: gamesapi
            - name: DB_HOST
              value: db

---
apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  selector:
    app: web
  ports:
    - port: 80
      targetPort: 8000
  type: LoadBalancer
