"""init_db

Revision ID: 43a9160f74dd
Revises: 
Create Date: 2023-07-05 22:39:16.651730

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '43a9160f74dd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('pk_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('total_kills', sa.Integer(), nullable=False),
    sa.Column('kills', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('pk_id')
    )
    op.create_table('players',
    sa.Column('pk_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('game_pk_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_pk_id'], ['games.pk_id'], ),
    sa.PrimaryKeyConstraint('pk_id')
    )
    op.create_index(op.f('ix_players_game_pk_id'), 'players', ['game_pk_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_players_game_pk_id'), table_name='players')
    op.drop_table('players')
    op.drop_table('games')
    # ### end Alembic commands ###
