"""modify

Revision ID: 739903f1b2ec
Revises: 2ce2933d7deb
Create Date: 2023-07-04 10:25:28.710848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '739903f1b2ec'
down_revision = '2ce2933d7deb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('total_kills', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'total_kills')
    # ### end Alembic commands ###
